from core.exceptions import BaseError


class UserNotFoundError(BaseError): ...
